### ISSUE TITLE
데이터셋 다운로드

### ISSUE THREAD

**Issue by hjpark2017** [jinulee-v/kmdp#1]
안녕하세요.
형태소 기반 의존구문분석 꼭 돌려보고 싶은데요~
데이터셋 VictorNLP_kor(Modu) 어디서 다운로드 받을 수 있는지요?
감사합니다.

**Comment by jinulee-v** [comment]
안녕하세요,
관심 가져주셔서 감사드립니다.

모두의 말뭉치를 기반으로 만들어진 데이터셋이라, 사용협약으로 인해 데이터셋을 직접 올려서 공유할 수 없는 점 양해 부탁드립니다.
국립국어원 모두의 말뭉치 홈페이지에서 `구문분석 말뭉치(v2.0)` `형태소 분석 말뭉치(v1.0)` 를 사용 신청해주세요!

https://corpus.korean.go.kr/request/reausetMain.do

2월 10일 이전에 모두의 말뭉치로부터 직접 변환 가능한 스크립트를 비롯한 다양한 유틸리티 코드를 합쳐서 추가하도록 하겠습니다.
이슈 알림에 귀기울여 주세요!

**Comment by hjpark2017** [comment]
친절하고 빠른 답변 넘 감사드립니다!
이슈 알림 잘 체크하고 있을게요!

2023년 2월 2일 (목) 오후 7:05, Jinu Lee ***@***.***>님이 작성:

**Comment by jinulee-v** [comment]
현재 제공되는 스크립트 중 `1_preprocess.sh` 의 테스팅이 완료되었습니다!

한 번의 스크립트 실행으로 모두의 말뭉치를 KMDP 형식으로 변환하여 사용하실 수 있도록 되어 있으니 참고 바랍니다.
의존 구문 분석기 학습 스크립트는 곧 추가로 테스팅할 예정입니다!
문의사항이 있으시다면 이슈나 메일로 연락 주세요!

- 이진우 드림

**Comment by hjpark2017** [comment]
넘 감사합니다!
알려주신 구문 말뭉치는 다운 받았는데, 형태소 말뭉치는 아직 승인 처리가 안 되었네요... 완료되는 대로 1_preprocess.sh 돌려볼게요!
